### ISSUE TITLE
learnyounode 6:make it modular

### ISSUE THREAD

**Issue by liuestc** [nodeschool/discussions#1611] opened 2016-01-14 15:21 UTC
my code:
main.js
```js
var mymodule = require('./module.js');
mymodule(process.argv[2],process.argv[3],function(err,list){
    if (err) {
        console.log(err);
    } else {
        list.forEach(function(file) {
            console.log(file);
        });
    }
});
```

module.js
```js
var path=require("path");
var fs=require("fs");
module.exports=function(dir,ext,callback){
    fs.readdir(dir,function(err,file){
        if(err){
            callback(err);
        }
        new_file=file.filter(function(item){
            if(path.extname(item)==="."+ext)
                return item;
        });
      callback(null,new_file);
    })
};
```

G:\learnnode\module.js:30
        new_file=file.filter(function(item){
                     ^

TypeError: Cannot read property 'filter' of undefined
    at G:\learnnode\module.js:30:22
    at FSReqWrap.oncomplete (fs.js:82:15)

How to solve？
3Q!

**Comment by titoesteves** [comment] 2016-01-17 08:46
In your error handling I would change it from to `callback(err)` to `return callback(err)`. The reason being is that if there is an error, it will not continue to the subsequent code below which may explain why the error shows undefined.

**Comment by fruitl00p** [comment] 2016-02-26 07:45
This seems to be a duplicate of #1611 one might want to close this want and solve the other ;)

And yes, i had the same problem last night doing a class and missing the `return` statement (either via `return callback(err);` or via `callback(err); return;` fixed it..

**Closed** 2016-03-12 13:38 UTC
Labels: learnyounode
