### ISSUE TITLE
Javascripting Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by theintrovextrov** [nodeschool/discussions#1927] opened 2016-11-17 01:41 UTC
{ Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:264:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
  cmd: 'node "/Users/TheIntrovExtrov/Desktop/javascripting/for-loop.js"' }
javascripting javascripting verify for-loop.js

```

### My Code
```
var total = 0
var limit = 10
for (var i = 0; i < limit; total += i) {
  console.log(i)
}
```

**Comment by ishtiaque23** [comment] 2016-11-17 04:28
The exit logic for the For loop is broken here. Because of that, its becoming an infinite loop.
 
Your code is setting a starting value of **i** as 0. Then its saying the condition will be **I** is less than **limit** which is 10. But then at the increment section you are increasing the value of **total**, instead of **i**. 

So, in your case **i** is always staying 0 and as it is less than 10, the loop will keep on printing 0 infinite times(until it run out of buffer)

To fix this, you need to work on the **total += i** part of your code.

Give it another try and let us know.

**Comment by theintrovextrov** [comment] 2016-11-21 15:26
Yeah. I wasn't incrementing, so the _i_ was always 0. I changed the **total += i** to **i++** and the problem was solved. Thanks!

**Comment by riyadhalnur** [comment] 2016-11-21 15:52
Closing this since it seems the problem is solved. Please feel free to re-open if premature.

**Closed by riyadhalnur** 2016-11-21 15:52 UTC
Labels: javascripting, waiting-for-feedback
