### ISSUE TITLE
learnyounode install hang

### ISSUE THREAD

**Issue by lheneks** [nodeschool/discussions#1849] opened 2016-08-19 21:04 UTC
* windows 8.1
* node version: 4.5.0
* npm version:  2.15.9

I am trying to install learnyounode, but npm just hangs indefinitely.  
I ran > npm -g --verbose install learnyounode
It stops at the same spot every time.  I have tried powershell, regular command shell, unintstall/reinstall/restart machine etc.  I also tried installing various other versions of learnyounode (3.5.0, 3.4.0, 3.0.0) and they all hang as well, just at different spots.  Any ideas?

full log
[ouput.txt](https://github.com/nodeschool/discussions/files/427871/ouput.txt)

### end of npm output
```
npm verb about to build C:\users\me\node_modules\learnyounode\node_modules\workshopper-exercise
npm info build C:\users\me\node_modules\learnyounode\node_modules\workshopper-exercise
npm info linkStuff workshopper-exercise@2.7.0
npm verb linkBins workshopper-exercise@2.7.0
npm verb linkMans workshopper-exercise@2.7.0
npm verb rebuildBundles workshopper-exercise@2.7.0
npm verb rebuildBundles [ 'chalk',
npm verb rebuildBundles   'i18n-core',
npm verb rebuildBundles   'split',
npm verb rebuildBundles   'tuple-stream',
npm verb rebuildBundles   'wcstring',
npm verb rebuildBundles   'xtend' ]
npm info install workshopper-exercise@2.7.0
npm info postinstall workshopper-exercise@2.7.0
npm verb unlock done using C:\Users\me\AppData\Roaming\npm-cache\_locks\workshopper-exercise-4cd62f09cdacad8a.lock for C:\users\me\node_modules\learnyounode\nod
e_modules\workshopper-exercise
```

If I kill the install once it hangs and try to run the app, I get

### Error output
```
^CTerminate batch job (Y/N)? y
PS C:\users\me\documents\dev\node> learnyounode
learnyounode : The term 'learnyounode' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ learnyounode
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (learnyounode:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by buck06191** [comment] 2016-08-20 10:15
Just like to say that I get the same problem, stopping at the same point, using a Windows 10 64 bit PC, running from admin privileges powershell

**Comment by martinheidegger** [comment] 2016-08-21 00:48
Seems like a `npm` problem. It would be good to downgrade to a slightly older version (hopefully npm doesn't crash).

**Comment by lcmoba** [comment] 2016-08-21 11:59
The same problem here! 

Tried out with the latest version of NPM and previous versions such as 2.14.2 and still not working!!!

**Comment by suvjunmd** [comment] 2016-08-21 18:11
Same error

![npm](https://cloud.githubusercontent.com/assets/11020536/17838986/b9847b4a-67e3-11e6-825e-a6df5262a4d6.png)

**Comment by abolajibisiriyu** [comment] 2016-08-21 23:29
I'm having the same Issue.

**Comment by fayyazpoonawala** [comment] 2016-08-22 00:40
Same problem here
![image](https://cloud.githubusercontent.com/assets/5894936/17840896/50995492-67c6-11e6-86c3-9f9fd664c43e.png)

**Comment by gugonzar** [comment] 2016-08-22 01:04
Same problem in Windows 7 ...
![image](https://cloud.githubusercontent.com/assets/21163033/17841085/6dd35a3a-67da-11e6-93a9-6b6abba61241.png)

**Comment by btkarthick** [comment] 2016-08-22 07:59
Seems the issue is with some of the workshops. I able to install lololodash successfully.

**Comment by khanhoct** [comment] 2016-08-22 10:06
Same problem when install javascripting module. Maybe `npm` has problem.

**Comment by martinheidegger** [comment] 2016-08-22 10:19
I created an issue on NPM: https://github.com/npm/npm/issues/13722

**Comment by abolajibisiriyu** [comment] 2016-08-22 12:06
This issue is taking time to fix.. Can anyone one suggest an npm version that works well with these workshops..

**Comment by martinheidegger** [comment] 2016-08-22 12:14
Try `3.9` ?

**Comment by jtrollkarl** [comment] 2016-08-22 12:21
Still hangs for me with npm 3.9.0

**Comment by martinheidegger** [comment] 2016-08-22 12:22
I don't have a windows machine handy. Would you mind to triage?

**Comment by jtrollkarl** [comment] 2016-08-22 12:26
Sorry I'm new to node. What is meant by 'triage'?

**Comment by martinheidegger** [comment] 2016-08-22 12:57
triage is a general term (not node specific). Just try out versions, say the bug happened in version 3.5.3: 
npm latest
npm 3.0 (one major down, working so next is up)
npm 3.5 (one half step, working so next is up)
npm 3.7.5 (broken so next is down)
npm 3.6.0 (broken so next is down)
npm 3.5.2 (working so next is up)
npm 3.5.3 (broken, so we know it happended 3.5.3 -> 3.5.3)

**Comment by khanhoct** [comment] 2016-08-22 15:15
@martinheidegger : How to install npm 3.5.2?. My current version is 2.15.9

**Comment by ismnoiet** [comment] 2016-08-22 15:23
@khanhoct you can install the amazing [n](https://github.com/tj/n) npm module to install and manage different Nodejs versions.

**Comment by martinheidegger** [comment] 2016-08-22 15:26
@ismnoiet He asked for **npm** not **node**. npm can **usually** be up and downgraded using `npm i npm@<version> -g` but this can break so you might need to install node & npm if it breaks.

**Comment by khanhoct** [comment] 2016-08-22 15:33
I installed npm 3.5.2 and tried command `npm install -g learnyounode` . But It stoped at:
 
extract:learnyounode      ▄ ╢█████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░╟

Sad.

**Comment by martinheidegger** [comment] 2016-08-22 15:45
@khanhoct `npm i --verbose` will show the output that is usually stored in `npm-debug.log`

**Comment by ishtiaque23** [comment] 2016-08-22 16:48
Adding my two cents here. A completely different approach. @martinheidegger feel free to move it to somewhere more meaningful if you find it out of context for this thread)


People who are using windows 10 can get the **anniversary update**. In that update they will get an linux bash shell. This bash is a full fledge linux running within the windows setup. You can run most of the linux commands inside it.

So a workaround for windows user can be:
1. Get Windows 10
2. Get the windows 10 anniversary update(auto update)
3. Enable the BASH on Ubuntu [see instruction here](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)
4. Open the BASH
5. Install NVM [see instruction here](http://www.liquidweb.com/kb/how-to-install-nvm-node-version-manager-for-node-js-on-ubuntu-12-04-lts/)
6. Using NVM install your desired version of node(npm will be installed with it)
7. Now check the installation by running **which node** and **which npm**. You can check the version as well.
8. You are all set to install the modules. Try running **npm install -g learnyounode**

When inside bash, if any of the command does not work its mostly due to permission issue. Try using **sudo** in such case.

FYI, I don't use windows for my development work. I do have a gaming PC running windows 10. After seeing this issue thread with windows. I followed the exact steps(I mentioned above) in that machine and was able to install both **javascripting** and **learnyounode**. So I can assure that if you follow the instructions properly, you will be able to make it work perfectly.

NOTE: This BASH provided by windows may not be the best thing but this definitely help out the learning phase of node. Also as you are using linux commands here, people like us who spends most of their time either on mac or linux will be able to help faster and confidently.

**Comment by lheneks** [comment] 2016-08-22 17:43
I tried with some other npm versions
3.0 - fails
2.0 - fails
1.4.16 - fails

One thing I forgot to note in my OP is that I can install other modules without issue

**Comment by martinheidegger** [comment] 2016-08-22 18:48
@lhenecks it might have to do with a Problem on the npm Server (a broken tar.gz in a recent Release)

**Comment by khanhoct** [comment] 2016-08-23 04:40
I tried to install learnyounode on c9.io (cloud IDE) and successful (c9.io is linux system)

```
khanhoct:~/workspace $ node --version
v4.4.5
khanhoct:~/workspace $ npm --version
2.15.5
```

And I installed node 4.4.5 and npm 2.15.5 on my windows 10 laptop, but fails, maybe there is differences between the Linux and Windows

**Comment by gugonzar** [comment] 2016-08-23 04:47
Using --verbose to see the exact point where the installation script fails:

![image](https://cloud.githubusercontent.com/assets/21163033/17880617/cd140b00-68c2-11e6-8281-61eccbf04587.png)

**Comment by martinheidegger** [comment] 2016-08-24 01:04
Turns out it has been my fault. I published a new version. Would you mind trying to install it again?

**Comment by suvjunmd** [comment] 2016-08-24 04:56
It works :+1:

**Comment by martinheidegger** [comment] 2016-08-24 06:57
@lheneks @buck06191 @lcmoba @suvjunmd @abolajibisiriyu @fayyazpoonawala @gugonzar  @btkarthick @khanhoct @jtrollkarl @ismnoiet @ishtiaque23 Thank you for your support and patience. Your input was very helpful!

**Closed by martinheidegger** 2016-08-24 06:57 UTC
Labels: installation, learnyounode, windows
