### ISSUE TITLE
Windows path for how-to-npm broken

### ISSUE THREAD

**Issue by jonoruss** [nodeschool/discussions#1054] opened 2015-04-06 18:22 UTC
Hey guys,

So I'm running through how-to-npm on windows, and for a few of the lessons ("install npm" and "Login"), I can't verify the solution. The trouble is I've installed node.js in C:\Program Files\nodejs, and so I get the following:

```
C:\Workspaces\node_sandbox\how-to-npm>how-to-npm verify
verifying that npm is installed...
Uh oh!  npm had a problem! {"killed":false,"code":1,"signal":null,"cmd":"C:\\Windows\\system32\\cmd.exe /s /c \"C:\\Program Files\\nodejs\\npm.CMD --version\""}
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

It seems it doesn't like the space in "Program Files". For the basics, this is fine (I know that npm is installed, if it wasn't, I wouldn't be able to get the module!), but for the more advanced lessons where I want my work to be checked, this is a problem.

Anyone have any ideas, aside from re-installing in a different folder?

**Comment by martinheidegger** [comment] 2015-04-06 18:36
Duplicate of this, i guess: https://github.com/npm/how-to-npm/issues/11

**Closed by martinheidegger** 2015-04-06 18:36 UTC
Labels: how-to-npm, windows

**Comment by jonoruss** [comment] 2015-04-06 18:55
Ahh thank you. Sorry I couldn't find the original defect when I opened this one! :O
