### ISSUE TITLE
Navigation is not working on windows 8.1

### ISSUE THREAD

**Issue by riapp** [nodeschool/discussions#1544] opened 2015-11-18 04:06 UTC
I just installed javascripting and learnyounode npm packages
Got it all running fine but both cant navigate on the list of menu items.

![image](https://cloud.githubusercontent.com/assets/1283734/11232318/c3048fd8-8e05-11e5-94b4-6fcdeb849802.png)

BTW I am running widows on mac with bootcamp cold it be a problem?

**Comment by SomeoneWeird** [comment] 2015-11-18 04:12
Known issue with older versions of node, it's fixed in `5.1.0`, see #1448

**Comment by riapp** [comment] 2015-11-18 04:12
Just was this https://github.com/nodeschool/discussions/issues/1448 and they saying that there is an issue with this https://github.com/substack/terminal-menu/issues/34 hopefulli it will be fixed soon

**Closed by SomeoneWeird** 2015-11-18 04:12 UTC

**Comment by SomeoneWeird** [comment] 2015-11-18 04:15
The issue is with node, and has been fixed in the latest stable version.

**Comment by riapp** [comment] 2015-11-18 04:21
OK got is. Just updated to 5.1.0 and all looking good. Thanks for help.
