### ISSUE TITLE
I'm trying to install Express for Windows 10 with node.js v6, I get this error when installing

### ISSUE THREAD

**Issue by yuvilla** [nodeschool/discussions#1891] opened 2016-10-03 15:26 UTC
I'm trying to install Express for Windows 10 with node.js v6, I get this error when installing
* node version v6.6.0: <run "node -v" in you terminal and replace this>
* npm version 3.10.3:  <run "npm -v" in you terminal and replace this>

### Error output
```
G:\server_node\express>npm install express --save
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ENOSELF

npm ERR! Refusing to install express as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\server_node\express\npm-debug.log
```

### My Code
```js
 // copy your code here
```

**Comment by riyadhalnur** [comment] 2016-10-03 15:32
Hi, @yuvilla, this particular error is caused by naming the folder the same as the name of one of the packages you are trying to install. So if you are installing `express`, you can't name the folder `express`. Try changing the name to something else and it should work fine. 😃

**Comment by yuvilla** [comment] 2016-10-03 16:01
Thank you @riyadhalnur , it was very useful to me your recommendation. And solve the problem, success

**Comment by riyadhalnur** [comment] 2016-10-03 16:03
Glad it worked out. Closing the issue then since it's resolved.

**Closed by riyadhalnur** 2016-10-03 16:03 UTC
Labels: installation, question, waiting-for-feedback, windows
