### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by lohithkumarnadella** [nodeschool/discussions#1942] opened 2016-12-15 10:00 UTC
* node version: v7.2.1
* npm version:  3.10.10
* os:mac

Tried: npm install -g javascripting

Getting this issue

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "javascripting"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lohithkumar/npm-debug.log

**Comment by zhdzmn** [comment] 2016-12-15 10:49
duplicate of https://github.com/nodeschool/discussions/issues/1943

**Closed by zhdzmn** 2016-12-15 10:49 UTC
Labels: installation, javascripting
