### ISSUE TITLE
Why i'm getting an image as background for http://nodeschool.io/#workshoppers ?

### ISSUE THREAD

**Issue by ismnoiet** [nodeschool/discussions#1548] opened 2015-11-19 16:56 UTC
Why i'm getting an image as the background (http://nodeschool.io/#workshoppers) when i zoom out 67%, just before the core section, is it an error or something else?
try it and tell me what you get

**Comment by riyadhalnur** [comment] 2015-11-20 05:34
@ismnoiet There's full-width image between the Core and Workshoppers section. It's meant to be there.

**Comment by ismnoiet** [comment] 2015-11-20 07:40
@riyadhalnur but it is  hidden, is it used for any purposes ?

**Comment by martinheidegger** [comment] 2015-11-20 07:56
@ismnoiet Screenshot might be adding to your explanation!

**Comment by ismnoiet** [comment] 2015-11-20 08:08
@martinheidegger  Here is a snapshot when you zoom out 67%

![this](https://cloud.githubusercontent.com/assets/5025240/11294744/220f1d52-8f66-11e5-9866-b02c1959d611.png)

**Comment by martinheidegger** [comment] 2015-11-20 08:14
What you are seeing is the effect of this css rule: https://github.com/nodeschool/nodeschool.github.io/blob/3dd5b348121e1dd1153dd516c1f9831830d6c6e1/style.css#L197 It specifies that the image is not shown if the screen is smaller than 1366px. If you scale it will process the site as if it were bigger and add the image. This image is there by design (to make the page look "better") for bigger screens.

**Comment by ismnoiet** [comment] 2015-11-20 08:18
@martinheidegger ahhh, are saying  that this is a responsive stuff ?,
i thought it is an error or something else.
Thank you for the clarification

**Comment by martinheidegger** [comment] 2015-11-20 08:32
No problem, yes it is on purpose :smile:  I close this issue if you dont mind ;)

**Closed by martinheidegger** 2015-11-20 08:32 UTC
Labels: homepage
