### ISSUE TITLE
functional-javascript-workshop `lodash` dependancy?

### ISSUE THREAD

**Issue by tbelaire** [nodeschool/discussions#1096] opened 2015-04-21 22:30 UTC
I'm attempting functional-javascript-workshop, and I'm having a strange error on problem 2.
Version: functional-javascript@1.0.0

```
// p2.js
module.exports = function (f, num) {
    for(int i = 0; i<num; i++) {
        f();
    }
};
```

```
⚡ fjs run p2.js
✗ You need to install all of the dependencies you are using in your solution (e.g. lodash)
------------------------
/usr/local/lib/node_modules/functional-javascript-workshop/exercises/runner.js:103
  return fx.apply(null, input)
           ^
TypeError: Cannot read property 'apply' of undefined
    at obtainResult (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/runner.js:103:12)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/runner.js:68:27)
    at next (/usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper-exercise/exercise.js:177:19)
    at /usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper-exercise/exercise.js:184:7
    at Exercise.<anonymous> (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/runner.js:28:16)
    at next (/usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper-exercise/exercise.js:177:19)
    at /usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper-exercise/exercise.js:184:7
    at /usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper-exercise/execute.js:97:7
    at process._tickCallback (node.js:355:11)
```

What is `lodash`, and why would I need to depend on it?  Aren't I just writing pure js?

**Comment by martinheidegger** [comment] 2015-04-22 04:26
This seems to be a usability bug! The workshopper treats every error as "missing requirement".  The problem is that you specified the variable with `int i` while in javascript this should be `var i`.

Note to @timoxley shouldn't there be a separate error that is shown when the solution throws an error here: https://github.com/timoxley/functional-javascript-workshop/blob/aa7812e42f8ca60cbe04f2b1f907bf93c534f6e6/exercises/runner.js#L25

**Comment by tbelaire** [comment] 2015-04-22 18:21
Durr, that's a dumb error. 

Would this also be a good place to point out that saying as a hint ` This is really simple.` sounds rather condescending when I've gotten stuck on it.  Wording it as something like: `Don't overthink it, the code should be rather simple` would sound *much* friendlier.

Other things to adjust would be making the `boilerplate` sections match the final solutions, and explicitly calling out the `module.exports` requirement of the first task in functional-javascript-workshop, since it's only mentioned in the boilerplate section, which was rather confusing at first.

**Comment by martinheidegger** [comment] 2015-04-22 18:39
Created a PR to make it more friendly :+1:

**Comment by tbelaire** [comment] 2015-04-22 18:57
Great!

While I'm at it, the official solution for implementing `reduce` breaks the conditions set out, and
introduces a helper function `reduceOne`, after explicitly saying that helper functions are not allowed.

**Comment by SomeoneWeird** [comment] 2015-06-23 11:23
PR was merged upstream, closing.

**Closed by SomeoneWeird** 2015-06-23 11:23 UTC
Labels: contains-hint-for-improvement, functional-javascript-workshop
