### ISSUE TITLE
Cannot Find work-shopper excerise

### ISSUE THREAD

**Issue by Ap0ph1s** [nodeschool/discussions#978] opened 2015-03-03 22:11 UTC
Trying to do ExpressWorks, and tried installing workshopper-excerise, but It still crashes and I can't do any of its tutorials

**Comment by empireconstruct** [comment] 2015-03-04 02:24
Having a a similar issue, have  you found a solution?

**Comment by Ap0ph1s** [comment] 2015-03-04 02:46
No :(

**Comment by empireconstruct** [comment] 2015-03-04 02:58
While you're waiting for a proper solution, try reverting back to a previous version of expressworks.

**Comment by SomeoneWeird** [comment] 2015-03-04 05:57
Can you paste the actual error please?

**Comment by empireconstruct** [comment] 2015-03-04 13:37
Error: Cannot find module 'workshopper-exercise' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Module.require module.js:364:17)                                            at require (module.js:380:17) at Object.<anonymous (C:\Users\Anita\AppData\Roaming\npm\node_modules\expressworks\exercises\hello_world\exercise.js:3:21) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10)                             at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17)

**Comment by martinheidegger** [comment] 2015-03-05 01:39
Duplicate of https://github.com/azat-co/expressworks/issues/60 Should really be fixed :(

**Comment by martinheidegger** [comment] 2015-03-05 01:40
@azat-co maybe you can merge: https://github.com/azat-co/expressworks/pull/61

**Closed by martinheidegger** 2015-03-05 01:39 UTC
Labels: expressworks

**Comment by ddelrio1986** [comment] 2015-03-12 02:46
Just run npm install -g workshopper-exercise to get around the issue.
