### ISSUE TITLE
learnyournode error

### ISSUE THREAD

**Issue by kokoh93** [nodeschool/discussions#2142] opened 2017-07-25 00:29 UTC
I'd like to use the learnyournode module but I keep getting an error. Where can I find it or does it not exist anymore?

Khadijahs-MBP:~ keodijah$ npm install -g learnyournode
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "learnyournode"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/learnyournode
npm ERR! 404 
npm ERR! 404  'learnyournode' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/keodijah/npm-debug.log

**Comment by RedSparr0w** [comment] 2017-07-25 01:19
This would be because of the extra letter :smile: 

it is 'learnyounode'
not 'learnyou*r*node'
(without the 'r' in 'your')

**Comment by kokoh93** [comment] 2017-07-25 10:49
Yea I noticed it a couple of minutes later 🤣 Thank you !

**Comment by stefanmirck** [comment] 2017-07-28 15:03
Closing since the issue is solved.

**Closed by stefanmirck** 2017-07-28 15:03 UTC
Labels: learnyounode
