### ISSUE TITLE
learnyounode problem 3

### ISSUE THREAD

**Issue by anshul313** [nodeschool/discussions#1211] opened 2015-06-10 11:24 UTC
i am not able to understand the problem no 3 of learnyounode, please provide me with the solution and explanation.

**Comment by martinheidegger** [comment] 2015-06-11 11:28
@anshul313 Hello! If is hard for me to write an explanation without knowing what the problem is for you with problem 3. Do you think you can explain your problem a bit better?

**Comment by singhal451** [comment] 2015-06-12 12:56
I just have to write learnyounode verify program.js to verify???

**Comment by singhal451** [comment] 2015-06-12 13:03
I done......
@anshul313  if you want help just let me know

**Comment by anshul313** [comment] 2015-06-13 17:08
plz explain me solution of that problem ...

**Comment by smoleniuch** [comment] 2015-06-14 11:52
hi,can you tell me how to get path file for this text file from problem number 3?sorry but im new in programming and i dont know how to find it.Instructions says that full path file will be provided but how?thanks for your time

**Comment by SomeoneWeird** [comment] 2015-06-14 12:12
It will be provided as a command line argument, so it will be in the array `process.argv`

**Comment by singhal451** [comment] 2015-06-15 04:27
var fs = require('fs')
    var path = require('path')
    
    fs.readdir(process.argv[2], function (err, list) {
      list.forEach(function (file) {
        if (path.extname(file) === '.' + process.argv[3])
          console.log(file)
      })
    })

**Comment by anonRegions** [comment] 2015-06-16 15:45
@singhal451: I'm confused by your code above because I thought we were writing synchronous I/O, according to which, should you be using readdirSync? Please advise.

**Comment by zeallous** [comment] 2015-07-26 11:00
hi so any updates on this?

**Comment by zeallous** [comment] 2015-07-26 11:01
@singhal451 any hints (or even the solution) for this question?

**Comment by SomeoneWeird** [comment] 2015-07-26 11:22
@zeallous what are you stuck on?

**Comment by SomeoneWeird** [comment] 2015-08-29 06:31
Please open another issue if needed.

**Closed by SomeoneWeird** 2015-08-29 06:31 UTC
Labels: learnyounode
